### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [1]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [2]:
a=999

### Convert a tensor to scalar

In [3]:
a=torch.tensor(a)
print(a)

tensor(999)


### Creating 2D tensor

In [4]:
b = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(b)
print(b.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


## Tensor and Numpy

### Convert from tensor to numpy array

In [5]:
n = a.numpy()
print(a)
print(n)

tensor(999)
999


### Convert from numpy array to tensor

In [6]:
c = torch.from_numpy(n)
print(n)
print(c)

999
tensor(999)


## PyTorch and GPU

check if GPU is available

In [7]:
torch.cuda.is_available()

True

## Basic operations

In [8]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

print(x + y)
print(x * y)

tensor([5, 7, 9])
tensor([ 4, 10, 18])


### Matrix multiplication

In [9]:
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

result = tensor_a @ tensor_b
print(result)

tensor([[19, 22],
        [43, 50]])


### Matrix transpose

In [10]:
print(result.T)

tensor([[19, 43],
        [22, 50]])


## Creating a specific type of tensor

In [11]:
a= torch.zeros(2, 2)
b= torch.rand(3, 3)
c= torch.eye(3)
d= torch.arange(0, 10)

print(a)
print(b)
print(c)
print(d)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.4914, 0.1643, 0.9522],
        [0.6013, 0.9213, 0.5527],
        [0.2203, 0.7710, 0.8387]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## Tensor's shape

### Checking the shape of a tensor

In [12]:
x= torch.rand(2, 3)
print(x.shape)

torch.Size([2, 3])


### Changing the shape of a tensor

In [13]:
z = torch.arange(12)
new_z = z.reshape(3, 4)
print(z)
print(new_z)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [14]:
x = torch.zeros(2, 2)
y = torch.ones(2, 2)

print(x)
print(y)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [15]:
# concatenate
combined = torch.cat([x, y], dim=1) # ต่อกันในแนวคอลัมน์
print(combined)

tensor([[0., 0., 1., 1.],
        [0., 0., 1., 1.]])


### Squeezing a tensor (removing an extra dimension)

In [16]:
x = torch.zeros(1, 10) # Shape (1, 10)
print(x.shape)

torch.Size([1, 10])


In [17]:
x_squeezed = x.squeeze() # Shape (10,)
print(x_squeezed.shape)

torch.Size([10])


### Unsqueezing a tensor (adding an extra dimension)

In [18]:
# x_squeezed.shape = (10, )
x_unsqueezed = x_squeezed.unsqueeze(dim=0) # กลับมาเป็น (1, 10)
print(x_unsqueezed.shape)

torch.Size([1, 10])


## Indexing

In [19]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [20]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [30]:
X = torch.randn(200, 7)
b = torch.randn(8, 1)
e = torch.randn(200, 1)


In [31]:
ones = torch.ones(200, 1)

In [32]:
X = torch.cat((ones, X), dim=1)

In [33]:
y = X @ b + e
print(y)

tensor([[-9.0408e+00],
        [-6.2544e+00],
        [-1.0281e+01],
        [-3.4715e+00],
        [ 1.2124e-01],
        [-9.7653e+00],
        [-1.0755e+00],
        [-7.2433e+00],
        [-1.0018e+01],
        [-1.3070e-01],
        [-3.1506e+00],
        [-1.2309e+00],
        [-3.7356e+00],
        [-5.3912e+00],
        [ 6.0613e-01],
        [-7.1169e+00],
        [-1.8508e+00],
        [-4.6052e-01],
        [ 1.0167e+00],
        [-3.3904e+00],
        [-2.9162e+00],
        [ 4.1545e+00],
        [-7.0389e-01],
        [-4.5012e+00],
        [ 3.8481e+00],
        [-1.7445e+00],
        [-7.9771e+00],
        [-6.4676e+00],
        [-7.7223e-01],
        [-2.8447e+00],
        [-5.9090e-01],
        [-6.2606e+00],
        [-7.1263e-01],
        [-3.7229e+00],
        [-4.2889e+00],
        [-6.1664e+00],
        [-5.2814e+00],
        [-5.8466e+00],
        [-8.4921e-01],
        [-2.3394e+00],
        [ 5.9714e+00],
        [-1.1363e+00],
        [-3.8130e+00],
        [ 2

In [34]:
XT = X.t()
b_hat = torch.inverse(XT @ X) @ XT @ y


In [35]:
y_hat = X @ b_hat


In [36]:
y_np = y.numpy()
y_hat_np = y_hat.numpy()

mse = np.mean((y_np - y_hat_np)**2)



In [38]:
print(mse)


0.9635825
